const constants = {
    SUCCESS: 'SUCCESS',
    FAILED: 'FAILED',

    INVALID_METHOD: "INVALID_METHOD",

    INCOMPLETE_BODY: 'INCOMPLETE_BODY',

    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS'
}

export default constants